language: ruby
cache: bundler
env:
  - "RAILS_VERSION=4.2.6"
  - "RAILS_VERSION=master"
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby-9.0.5.0
  - rbx-3.13
before_install:
  - gem update bundler
matrix:
  fast_finish: true
  allow_failures:
    - env: RAILS_VERSION=master
  exclude:
    - rvm: 2.1.8
      env: "RAILS_VERSION=master"
